<?php
/**
 * Menu - WordPress Admin Menu Registration
 *
 * This file handles the registration of the plugin's admin menu page and
 * the enqueuing of all frontend assets (JavaScript and CSS) required for
 * the React-based newsletter editor interface.
 *
 * @package WpHubspotEdmEditor\Admin
 */

declare(strict_types=1);

namespace WpHubspotEdmEditor\Admin;

use Automattic\Jetpack\Assets;

/**
 * Class Menu
 *
 * Manages the WordPress admin menu integration for the EDM plugin.
 *
 * This class is responsible for:
 * - Adding a top-level menu item to the WordPress admin sidebar
 * - Enqueueing the compiled React application and its dependencies
 * - Providing initial state/configuration to the frontend application
 * - Rendering the root DOM element for the React app to mount
 *
 * The menu page serves as the host for the entire React-based newsletter
 * editor. When a user navigates to this page, the compiled JavaScript
 * bundle is loaded and the React application takes over rendering.
 *
 * Asset Loading Flow:
 * -------------------
 * 1. User navigates to admin menu page
 * 2. WordPress triggers 'load-{page}' hook
 * 3. We register our script enqueue on 'admin_enqueue_scripts'
 * 4. Scripts and styles are loaded with proper dependencies
 * 5. Initial state is injected as inline JavaScript
 * 6. React app mounts to #wp-hubspot-edm-editor-root
 */
class Menu
{
    /**
     * Initialize admin menu hooks.
     *
     * Registers the admin_menu action to add our menu page when
     * WordPress builds the admin menu.
     *
     * @return void
     */
    public function init(): void
    {
        add_action('admin_menu', [$this, 'addAdminMenu']);
    }

    /**
     * Add the plugin menu page to WordPress admin.
     *
     * Creates a top-level menu item with:
     * - Custom email icon (dashicons-email)
     * - Position 30 in the menu order
     * - 'manage_options' capability requirement
     *
     * Also registers the page load hook for enqueueing assets only on our page.
     *
     * @return void
     */
    public function addAdminMenu(): void
    {
        $primary_slug = WP_HUBSPOT_EDM_EDITOR_SLUG;

        // Add top-level menu page and capture the hook suffix
        $dashboard_page_suffix = add_menu_page(
            __('wp-hubspot-edm-editor Dashboard', 'wp-hubspot-edm-editor'),  // Page title
            __('wp-hubspot-edm-editor', 'wp-hubspot-edm-editor'),                             // Menu title
            'manage_options',                                                      // Capability
            $primary_slug,                                                         // Menu slug
            [$this, 'renderDashboardPage'],                                        // Render callback
            'dashicons-email',                                                     // Icon
            30                                                                     // Position
        );

        // Register hooks that only fire when our specific page loads
        // This ensures we don't enqueue scripts on every admin page
        add_action('load-' . $dashboard_page_suffix, [$this, 'dashboardAdminInit']);
    }

    /**
     * Initialize dashboard-specific admin hooks.
     *
     * Called only when our admin page is being loaded. Sets up the
     * script enqueueing to happen at the right time in the page lifecycle.
     *
     * @return void
     */
    public function dashboardAdminInit(): void
    {
        add_action('admin_enqueue_scripts', [$this, 'enqueueDashboardAdminScripts']);
    }

    /**
     * Enqueue all scripts and styles for the dashboard.
     *
     * This method loads:
     * - The compiled React application (scripts.js)
     * - The compiled CSS styles (scripts.css)
     * - All WordPress dependencies declared in the asset file
     * - Localized data (nonce, API root) for REST API access
     * - Initial application state (permissions, routes, version)
     *
     * The asset file (scripts.asset.php) is generated by @wordpress/scripts
     * during the build process and contains dependency information and
     * a version hash for cache busting.
     *
     * @throws \WP_Die If the asset file is missing (build hasn't been run)
     * @return void
     */
    public function enqueueDashboardAdminScripts(): void
    {
        $prefix = WP_HUBSPOT_EDM_EDITOR_SLUG;

        /*
        |----------------------------------------------------------------------
        | Asset File Validation
        |----------------------------------------------------------------------
        |
        | The asset file is generated by the build process and is required
        | for proper dependency management. If it's missing, the plugin
        | cannot function and we should inform the developer.
        |
        */
        $asset_file_path = WP_HUBSPOT_EDM_EDITOR_PLUGIN_DIR . 'assets/public/scripts.asset.php';

        if (!file_exists($asset_file_path)) {
            wp_die('Required asset file not found. Please run `npm run build:dashboard` for this plugin.');
        }

        // Load the asset manifest (contains dependencies and version hash)
        $asset_file = include $asset_file_path;

        /*
        |----------------------------------------------------------------------
        | CSS Dependencies
        |----------------------------------------------------------------------
        |
        | Some WordPress script handles include associated styles that need
        | to be enqueued. We iterate through dependencies and enqueue any
        | that are registered as styles.
        |
        */
        foreach ($asset_file['dependencies'] as $style) {
            wp_enqueue_style($style);
        }

        /*
        |----------------------------------------------------------------------
        | Main Application Script
        |----------------------------------------------------------------------
        |
        | The compiled React application bundle. Dependencies are pulled
        | from the asset file to ensure WordPress core scripts are loaded
        | in the correct order.
        |
        */
        wp_enqueue_script(
            $prefix . '-dashboard',
            WP_HUBSPOT_EDM_EDITOR_PLUGIN_URL . 'assets/public/scripts.js',
            $asset_file['dependencies'],
            $asset_file['version'],
            true // Load in footer
        );

        /*
        |----------------------------------------------------------------------
        | Main Stylesheet
        |----------------------------------------------------------------------
        |
        | Compiled CSS including component styles and global overrides.
        |
        */
        wp_enqueue_style(
            $prefix . '-style',
            WP_HUBSPOT_EDM_EDITOR_PLUGIN_URL . 'assets/public/scripts.css',
            [],
            $asset_file['version']
        );

        /*
        |----------------------------------------------------------------------
        | REST API Configuration
        |----------------------------------------------------------------------
        |
        | Provide the nonce and API root URL to the frontend for making
        | authenticated REST API requests.
        |
        */
        $script_data = [
            'nonce' => wp_create_nonce('wp_rest'),   // Security token for REST API
            'apiRoot' => esc_url_raw(rest_url()),    // Base URL for REST API
        ];
        wp_localize_script($prefix . '-dashboard', 'wpHubspotEdmEditorData', $script_data);

        /*
        |----------------------------------------------------------------------
        | Initial Application State
        |----------------------------------------------------------------------
        |
        | Inject configuration and state data that the React app needs
        | immediately on load, before any API calls are made.
        |
        */
        wp_add_inline_script($prefix . '-dashboard', $this->renderDashboardInitialState(), 'before');
    }

    /**
     * Generate the initial state JavaScript.
     *
     * Creates a JavaScript variable containing the initial application
     * state. This is injected before the main script loads.
     *
     * @return string JavaScript code defining wpHubspotEdmEditorPluginState variable
     */
    public function renderDashboardInitialState(): string
    {
        return 'var wpHubspotEdmEditorPluginState = ' . wp_json_encode($this->initialDashboardState()) . ';';
    }

    /**
     * Get the initial state data for the dashboard.
     *
     * Returns an array of configuration values and user permissions
     * that the React application needs on startup.
     *
     * @return array{
     *     apiRoute: string,
     *     assetsURL: string,
     *     version: string,
     *     permissions: array{isAdmin: bool, isEditor: bool}
     * }
     */
    public function initialDashboardState(): array
    {
        return [
            'apiRoute'    => 'wp-json/' . WP_HUBSPOT_EDM_EDITOR_SLUG . '/v1',   // REST API route prefix
            'assetsURL'   => WP_HUBSPOT_EDM_EDITOR_PLUGIN_URL . 'assets',       // URL to assets directory
            'version'     => WP_HUBSPOT_EDM_EDITOR_VERSION,                     // Plugin version
            'permissions' => [
                'isAdmin'  => current_user_can('manage_options'), // Can configure plugin
                'isEditor' => current_user_can('edit_posts'),     // Can edit newsletters
            ],
        ];
    }

    /**
     * Render the dashboard page HTML.
     *
     * Outputs the root DOM element that the React application will mount to.
     * The React app is responsible for all rendering within this container.
     *
     * @return void
     */
    public function renderDashboardPage(): void
    {
        echo '<div id="wp-hubspot-edm-editor-root"></div>';
    }
}
